name: rsa_id_number
description: A package that provides easy-to-use Dart utilities for validating and generating South African ID numbers, ensuring accuracy and compliance with the ID number format. Whether you need to verify existing IDs or create random ones, this package simplifies the process.
version: 0.0.5
homepage: 'https://github.com/makhosi6/rsa_id_number'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  luhn_algorithm: ^1.0.0+1
  meta: ^1.9.1

dev_dependencies:
  lint: ^2.0.0
  test: ^1.24.1
